---
- hosts: tag_Type_couchbaseserver_data_cluster1
  remote_user: ubuntu
  sudo: true
  vars:
    couchbase_server_data_path: "/mnt/cbdata"
    couchbase_server_index_path: "/mnt/cbdata"
    build_url: "https://s3.amazonaws.com/scalability-mcafee/builds/couchbase-server-enterprise_4.5.0-718-debian7_amd64.deb"
    deb_path: "/tmp/couchbase-server.deb"
  tasks:
    - name: mk filesystem
      shell: mkfs -t ext4 /dev/xvdb

    - name: mount /dev/xvdb
      shell: mount /dev/xvdb  /mnt

    - name: chown couchbase:couchbase for /mnt
      shell: chown couchbase:couchbase /mnt

    - name: mkdir cbdata directory
      shell: mkdir -p {{ couchbase_server_data_path }}

    - name: mkdir cbindex directory
      shell: mkdir -p {{ couchbase_server_index_path }}

    - name: chown couchbase:couchbase
      shell: chown couchbase:couchbase {{ couchbase_server_data_path }}

    - name: chown couchbase:couchbase
      shell: chown couchbase:couchbase {{ couchbase_server_index_path }}

    - name: download binary
      get_url: url="{{build_url}}" dest="{{deb_path}}"

    - name: install couchbase
      apt: deb="{{deb_path}}"

    - name: wait for install done
      wait_for: port=8091 delay=10
