---
- hosts: tag_Type_clients
  remote_user: ubuntu
  sudo: true
  vars:
   ops_main: 4000
   ops_small: 1000
   create_perc: 30
   get_perc: 60
   delete_perc: 10
   sizes: "128 256"
   bucket0: "default"
   bucket1: "bucket1"
   bucket2: "bucket2"
  tasks:
    - name: checkout client repo
      git: repo=https://github.com/couchbaselabs/gideon dest=gideon/
    - name: start workload for bucket0
      shell: "nohup python gideon.py --ops {{ops_main}} --create {{create_perc}} --get {{get_perc}} --delete {{delete_perc}} --hosts {{groups['orchestrator'][0]}} --bucket {{bucket0}} --sizes {{sizes}} &"
      args:
          chdir: gideon/
    - name: start workload for bucket1
      shell: "nohup python gideon.py --ops {{ops_small}} --create {{create_perc}} --get {{get_perc}} --delete {{delete_perc}} --hosts {{groups['orchestrator'][0]}} --bucket {{bucket1}}&"
      args:
          chdir: gideon/
    - name: start workload for bucket2
      shell: "nohup python gideon.py --ops {{ops_small}} --create {{create_perc}} --get {{get_perc}} --delete {{delete_perc}} --hosts {{groups['orchestrator'][0]}} --bucket {{bucket2}}&"
      args:
          chdir: gideon/

# do rebalances  @2x increments
- hosts: tag_Name_qecouchbaseserverdatacluster1node15:tag_Name_qecouchbaseserverdatacluster1node16
  vars:
    rest_port: 8091
    rest_user: "Administrator"
    rest_pass: "password"
    rest_port: 8091
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: set couchbase_server_cluster_primary_node variable
      set_fact:
        couchbase_server_cluster_primary_node: "{{ lookup('file', '../../temp_couchbase_server_cluster_primary_node') }}"

    - name: add 2 nodes
      shell: "{{cli_bin}} server-add -c {{couchbase_server_cluster_primary_node}}:{{rest_port}} --server-add={{couchbase_server_node}}:{{rest_port}} --server-add-username={{rest_user}} --server-add-password={{rest_pass}} -u {{rest_user}} -p {{rest_pass}}"
- hosts: tag_Name_qecouchbaseserverdatacluster1node0
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: rebalance
      shell: "{{cli_bin}} rebalance -c {{couchbase_server_node}} -u {{rest_user}} -p {{rest_pass}}"
    - name: wait for 10 minutes
      wait_for: timeout=600

- hosts: tag_Name_qecouchbaseserverdatacluster1node17:tag_Name_qecouchbaseserverdatacluster1node18
  vars:
    rest_port: 8091
    rest_user: "Administrator"
    rest_pass: "password"
    rest_port: 8091
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: set couchbase_server_cluster_primary_node variable
      set_fact:
        couchbase_server_cluster_primary_node: "{{ lookup('file', '../../temp_couchbase_server_cluster_primary_node') }}"

    - name: add 2 nodes
      shell: "{{cli_bin}} server-add -c {{couchbase_server_cluster_primary_node}}:{{rest_port}} --server-add={{couchbase_server_node}}:{{rest_port}} --server-add-username={{rest_user}} --server-add-password={{rest_pass}} -u {{rest_user}} -p {{rest_pass}}"
- hosts: tag_Name_qecouchbaseserverdatacluster1node0
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: rebalance
      shell: "{{cli_bin}} rebalance -c {{couchbase_server_node}} -u {{rest_user}} -p {{rest_pass}}"
    - name: wait for 10 minutes
      wait_for: timeout=600


- hosts: tag_Name_qecouchbaseserverdatacluster1node19:tag_Name_qecouchbaseserverdatacluster1node20
  vars:
    rest_port: 8091
    rest_user: "Administrator"
    rest_pass: "password"
    rest_port: 8091
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: set couchbase_server_cluster_primary_node variable
      set_fact:
        couchbase_server_cluster_primary_node: "{{ lookup('file', '../../temp_couchbase_server_cluster_primary_node') }}"

    - name: add 2 nodes
      shell: "{{cli_bin}} server-add -c {{couchbase_server_cluster_primary_node}}:{{rest_port}} --server-add={{couchbase_server_node}}:{{rest_port}} --server-add-username={{rest_user}} --server-add-password={{rest_pass}} -u {{rest_user}} -p {{rest_pass}}"
- hosts: tag_Name_qecouchbaseserverdatacluster1node0
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: rebalance
      shell: "{{cli_bin}} rebalance -c {{couchbase_server_node}} -u {{rest_user}} -p {{rest_pass}}"
    - name: wait for 10 minutes
      wait_for: timeout=600

- hosts: tag_Name_qecouchbaseserverdatacluster1node21:tag_Name_qecouchbaseserverdatacluster1node22
  vars:
    rest_port: 8091
    rest_user: "Administrator"
    rest_pass: "password"
    rest_port: 8091
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: set couchbase_server_cluster_primary_node variable
      set_fact:
        couchbase_server_cluster_primary_node: "{{ lookup('file', '../../temp_couchbase_server_cluster_primary_node') }}"

    - name: add 2 nodes
      shell: "{{cli_bin}} server-add -c {{couchbase_server_cluster_primary_node}}:{{rest_port}} --server-add={{couchbase_server_node}}:{{rest_port}} --server-add-username={{rest_user}} --server-add-password={{rest_pass}} -u {{rest_user}} -p {{rest_pass}}"
- hosts: tag_Name_qecouchbaseserverdatacluster1node0
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: rebalance
      shell: "{{cli_bin}} rebalance -c {{couchbase_server_node}} -u {{rest_user}} -p {{rest_pass}}"
    - name: wait for 10 minutes
      wait_for: timeout=600





- hosts: tag_Name_qecouchbaseserverdatacluster1node23:tag_Name_qecouchbaseserverdatacluster1node24
  vars:
    rest_port: 8091
    rest_user: "Administrator"
    rest_pass: "password"
    rest_port: 8091
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: set couchbase_server_cluster_primary_node variable
      set_fact:
        couchbase_server_cluster_primary_node: "{{ lookup('file', '../../temp_couchbase_server_cluster_primary_node') }}"

    - name: add 2 nodes
      shell: "{{cli_bin}} server-add -c {{couchbase_server_cluster_primary_node}}:{{rest_port}} --server-add={{couchbase_server_node}}:{{rest_port}} --server-add-username={{rest_user}} --server-add-password={{rest_pass}} -u {{rest_user}} -p {{rest_pass}}"
- hosts: tag_Name_qecouchbaseserverdatacluster1node0
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: rebalance
      shell: "{{cli_bin}} rebalance -c {{couchbase_server_node}} -u {{rest_user}} -p {{rest_pass}}"
    - name: wait for 10 minutes
      wait_for: timeout=600




- hosts: tag_Name_qecouchbaseserverdatacluster1node25:tag_Name_qecouchbaseserverdatacluster1node26
  vars:
    rest_port: 8091
    rest_user: "Administrator"
    rest_pass: "password"
    rest_port: 8091
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: set couchbase_server_cluster_primary_node variable
      set_fact:
        couchbase_server_cluster_primary_node: "{{ lookup('file', '../../temp_couchbase_server_cluster_primary_node') }}"

    - name: add 2 nodes
      shell: "{{cli_bin}} server-add -c {{couchbase_server_cluster_primary_node}}:{{rest_port}} --server-add={{couchbase_server_node}}:{{rest_port}} --server-add-username={{rest_user}} --server-add-password={{rest_pass}} -u {{rest_user}} -p {{rest_pass}}"
- hosts: tag_Name_qecouchbaseserverdatacluster1node0
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: rebalance
      shell: "{{cli_bin}} rebalance -c {{couchbase_server_node}} -u {{rest_user}} -p {{rest_pass}}"
    - name: wait for 10 minutes
      wait_for: timeout=600




- hosts: tag_Name_qecouchbaseserverdatacluster1node27:tag_Name_qecouchbaseserverdatacluster1node28
  vars:
    rest_port: 8091
    rest_user: "Administrator"
    rest_pass: "password"
    rest_port: 8091
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: set couchbase_server_cluster_primary_node variable
      set_fact:
        couchbase_server_cluster_primary_node: "{{ lookup('file', '../../temp_couchbase_server_cluster_primary_node') }}"

    - name: add 2 nodes
      shell: "{{cli_bin}} server-add -c {{couchbase_server_cluster_primary_node}}:{{rest_port}} --server-add={{couchbase_server_node}}:{{rest_port}} --server-add-username={{rest_user}} --server-add-password={{rest_pass}} -u {{rest_user}} -p {{rest_pass}}"
- hosts: tag_Name_qecouchbaseserverdatacluster1node0
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
    couchbase_server_node: "{{hostvars[ec2_ip_address]['ec2_private_dns_name']}}"
  tasks:
    - name: rebalance
      shell: "{{cli_bin}} rebalance -c {{couchbase_server_node}} -u {{rest_user}} -p {{rest_pass}}"
    - name: wait for 10 minutes
      wait_for: timeout=600



# done
- hosts: tag_Type_clients
  tasks:
    - name: done! stop clients
      shell: "ps aux | grep gideon | awk '{print $2}' | xargs -I '{}' kill -s 9 '{}'"
      ignore_errors: True

