- hosts: clients
  tasks:
    - name: stop clients
      shell: "killall python"
      ignore_errors: True


- hosts: orchestrator
  vars:
    rest_user: "Administrator"
    rest_pass: "password"
    bucket0: "default"
    bucket1: "bucket1"
    bucket2: "bucket2"
    cli_bin:  "/opt/couchbase/bin/couchbase-cli"
  tasks:
   - name: delete bucket0
     shell: "{{cli_bin}}  bucket-delete -c  {{inventory_hostname}} -u {{rest_user}} -p {{rest_pass}} --bucket={{bucket0}}"
   - name: delete bucket1
     shell: "{{cli_bin}}  bucket-delete -c  {{inventory_hostname}} -u {{rest_user}} -p {{rest_pass}} --bucket={{bucket1}}"
   - name: delete bucket2
     shell: "{{cli_bin}}  bucket-delete -c  {{inventory_hostname}} -u {{rest_user}} -p {{rest_pass}} --bucket={{bucket2}}"


- hosts: couchbaseservers
  vars:
   rest_user: "Administrator"
   rest_pass: "password"
   cli_bin:  "/opt/couchbase/bin/couchbase-cli"
   internal_ip: "{{hostvars[inventory_hostname]['internal']}}"
  tasks:
   - name: remove node
     shell: "{{cli_bin}} failover -c {{groups['orchestrator'][0]}} --server-failover={{internal_ip}} -u {{rest_user}} -p {{rest_pass}} --force"
     when: inventory_hostname != groups['orchestrator'][0]

- hosts: orchestrator
  vars:
   rest_user: "Administrator"
   rest_pass: "password"
   cli_bin:  "/opt/couchbase/bin/couchbase-cli"
  tasks:
   - name: rebalance out node
     shell: "{{cli_bin}} rebalance -c {{inventory_hostname}} --server-remove={{inventory_hostname}} -u {{rest_user}} -p {{rest_pass}}"

